### ISSUE TITLE
⚖️ 关于少于三科考试科目无法展示排行榜的问题

### ISSUE THREAD

**Issue by qianjunakasumi** [qianjunakasumi/ZhiXueRank#1]
此插件依赖于“发挥水平学科诊断”的值以计算您的名次。
已知在特定情况下（少于三科）时，发挥水平学科诊断不会显示，因此服务器不会返回此值，
造成数据缺失无法计算。这是已知的无法避免的问题。

**Comment by RCHINA-hu** [comment]
八科也无法正常显示？

**Comment by qianjunakasumi** [comment]
> 八科也无法正常显示？

若总分处不显示 “发挥水平学科诊断” 即无法正常显示。若您确认 “发挥水平学科诊断” 正常显示而不显示排行榜时，可新建 Issue 详细描述

**Comment by 1diamondplus** [comment]
是大于三科还是大于等于三科？

**Comment by 1diamondplus** [comment]
是少于三科还是少于等于三科？

**Comment by qianjunakasumi** [comment]
> 是少于三科还是少于等于三科？

看图的话应该是少于吧。

**Comment by immoses648** [comment]
是看生成考试报告的时候有没有生成全科报告的，没有就请求不了这个接口

**Comment by 1diamondplus** [comment]
> 是看生成考试报告的时候有没有生成全科报告的，没有就请求不了这个接口

好的，现在可以了

**Comment by wangwentao0111** [comment]
现在好像都不行了
