### ISSUE TITLE
插件已不再显示

### ISSUE THREAD

**Issue by EndstoneV** [qianjunakasumi/ZhiXueRank#12]
![image](https://github.com/user-attachments/assets/c046d9be-bf8d-4a87-b416-ba80fdf8d1ac)
如图，插件已不再显示，已经试过重新安装、更换浏览器等都无效。

**Comment by qianjunakasumi** [comment]
系接口 API 更改，patch 无法覆盖导致此问题

**Comment by qianjunakasumi** [comment]
已于 v1.0.7 https://github.com/qianjunakasumi/ZhiXueRank/blob/v1.0.7/main.js 中修复, close #12
