### ISSUE TITLE
可以大概讲下怎么实现的吗

### ISSUE THREAD

**Issue by 123ABCDF11345** [qianjunakasumi/ZhiXueRank#2]
https://www.zhixue.com/zhixuebao/report/exam/getSubjectDiagnosis 这个返回的数据Rank是怎么换算成排名的，或者如果方便的话能把整体实现逻辑介绍一下吗，本人不太会js，想通过其它语言实现一下，万分感谢！

**Comment by qianjunakasumi** [comment]
rank 就是百分数，乘上班级人数就可计算。

https://github.com/qianjunakasumi/ZhiXueRank/blob/c90c9ff78eb4305abe3149f50d96abf4b0985152/main.js#L59

**Comment by qianjunakasumi** [comment]
整体上包括调用 API 的 HOOK，取得响应中班级人数和上述 Rank 百分比数据，二者相乘即算出，并无复杂的逻辑。

**Comment by 123ABCDF11345** [comment]
好的，十分感谢！
