### ISSUE TITLE
显示了发挥学科水平诊断并且有4门学科，看不到排名

### ISSUE THREAD

**Issue by qk-kun** [qianjunakasumi/ZhiXueRank#3]
显示了发挥学科水平诊断并且有4门学科，看不到排名
<img width="678" alt="屏幕截图 2023-02-12 213131" src="https://user-images.githubusercontent.com/78490296/218314056-17f8695a-f496-4cdc-ab9a-6c801cfd6dad.png">

**Comment by qianjunakasumi** [comment]
方便打开 F12 + 刷新并在 network 下找到 zhixuebao/report/exam/getSubjectDiagnosis 开头的响应吗

**Comment by qk-kun** [comment]
找得到 看得到average 和myrank 
另外我在邮件里给你回复的话看得到吗

**Comment by qianjunakasumi** [comment]
尚未收到你的邮件

**Comment by qk-kun** [comment]
邮件已发 那多半是被吞了 只能通过这个issue和你沟通吗 能不能给你发qq邮箱之类的，刚刚在GitHub上打了半天的字提示网络异常(｡•́︿•̀｡)

**Comment by qianjunakasumi** [comment]
支持的邮箱列表：i@qianjunakasumi.ren,qianjunakasumi@outlook.com,qianjunakasumi@gmail.com,qianjunakasumi@qq.com

**Comment by qk-kun** [comment]
已发qq邮箱

**Comment by qianjunakasumi** [comment]
此问题由 URL 变化引起，已知对当前版本任何人失效

**Comment by qianjunakasumi** [comment]
问题已在 v1.0.3 临时修复
