### ISSUE TITLE
无法显示

### ISSUE THREAD

**Issue by wangwentao0111** [qianjunakasumi/ZhiXueRank#4]
![image](https://github.com/qianjunakasumi/ZhiXueRank/assets/110269797/0c7723d5-72e2-47bb-a5a7-d6d70d432436)

**Comment by qianjunakasumi** [comment]
https://github.com/qianjunakasumi/ZhiXueRank/issues/1#issuecomment-1441931417

**Comment by qianjunakasumi** [comment]
我这仍能正常显示
