### ISSUE TITLE
更精确的算法

### ISSUE THREAD

**Issue by zunao1024** [qianjunakasumi/ZhiXueRank#6]
# 抓包数据如下
![image](https://github.com/qianjunakasumi/ZhiXueRank/assets/75932537/1d275d9a-358d-403c-bc81-b11b484b3ea9)
注意看历史
# 原代码
```JavaScript
GLOBALDATA.data[id].subject[k].rank = Math.trunc(e.number * e.subject[k].org / 100) + 1;
```
![image](https://github.com/qianjunakasumi/ZhiXueRank/assets/75932537/4a593069-da52-4a69-9972-d02808faa760)
# 修改后代码
```JavaScript
GLOBALDATA.data[id].subject[k].rank = Math.ceil(e.number * e.subject[k].org / 100);
```
![image](https://github.com/qianjunakasumi/ZhiXueRank/assets/75932537/94471993-6cba-4a81-afab-24b884a162f6)

算法可能更精确

**Comment by qianjunakasumi** [comment]
你好，感谢你的建议，经过进一步验证得到：

```
function rank(percentage, totalPeople) {
    const rank = Math.ceil(percentage / 100 * totalPeople);
    return Math.min(Math.max(rank, 1), totalPeople);
}
```

能更有效地将 0-100% 映射到 1-x 人的排名中且不会出现排名为 0 或超出 x 范围的问题

如果方便的话你可 fork 本仓库后修改代码并提交 PR : )

**Comment by zunao1024** [comment]
你好，谢谢你的认可，我还不是很会提交pr，如果代码对你有帮助，请自己修改你的仓库内的代码😅

**Comment by qianjunakasumi** [comment]
reopen this issue for trace PR. do not close

**Comment by HShiDianLu** [comment]
排名的计算可以考虑为一个映射问题。
其计算方式应为 将 `[1, total]` 映射至 `[0, 100]`。
公式应为：`myRank  = 100 / (total - 1) * (position - 1)` （智学网保留了一位小数）
可以通过将 `[0, 100]` 映射回 `[1, total]` 求出排名。
`position = round(1 + (total - 1) / 100 * myRank)`
但由于数据存在不可避免的精度问题，因此可以枚举排名 `i` _(1<=i<=total)_，计算出对应的 `rank[i]`，当 `|myRank-rank[i]|` 的值最小时，`i` 即为排名。


（叠甲）以上方法还未经过实际验证，有待日后进行验证。

**Comment by qianjunakasumi** [comment]
@HShiDianLu 您可以新建一个 Issue 来提出新的建议
